version: '3'
services:
  frontend:
    network_mode: "bridge"
    container_name: uplift_frontend
    image: uplift_frontend_image
    ports:
      - "1337:1337"
    volumes:
      - .:/app
      - /app/node_modules
    command: /opt/entry.sh
